print('============= JOGO DA FORCA ============')
print('')
print('ESSE JOGO FOI DESENVOLVIDO PARA TESTAR AS MINHAS HABILIDADES EM PYTHON')
print('E PARA TESTAR MINHA CRIATIVIDADE.')
print()
print('jogo para jogar 2 ou mais pessoas')
print()

nome_mand = input('Digite o nome do Dono da FORCA: ')
nome_forc = input('Digite o Nome de quem esta na FORCA: ')
secreto = input(f'{nome_mand} escolha uma palavra secreta: ')
digitadas = []
contador = 0
print()
print()
print()
print()
print()
print()
print()
print()
print()
print()
print()
print()
print()
print()
print()
print()
print()
print()
print()
print()
print()
print()
print()
print()
print()
print()
print()
print()
print()
print()
print()
print()
print()
print()
print()
print()
print()
print()
print()
print()
print()
print()
print()
print()
print()
print()
print()
print()
print()
print()
print()
print()
print()
print()
print()
print()
print()
print()
print()
print()
print()
print()
print()
print()
print()
print()
print()
print()
print()
print()
print()
print()
print()
print()
print()
print()
print()
print()
print()
print()
print()
print()
print()
print()
print()
print()
print()
print()
print()
print()
print()
print()
print()
print()
print()
print()
print()
print()
print()
print()
print()
print()
print()
print()

while True:
    secreto_temporario = ''

    letra = input(f'{nome_forc} DIGITE UMA LETRA: ')
    contador += 1
    if len(letra) > 1:
        print()
        print('Ahhhh isso nao vale, digital apenas uma letra.')
        print(f'{nome_forc} nao tente roubar, como puniçao, numero total de tentativas')
        print('almentou em mais 5')
        contador = contador + 5
        print()
        continue

    digitadas.append(letra)

    if letra in secreto:
        print(f'{secreto_temporario:-^50}')
        print(f'UHUULLL, {nome_forc} a letra "{letra} " existe na palavra secreta. ')
    else:
        print()
        print(f'AFFFzzz, {nome_forc} a letra "{letra} " NAO EXISTE na palavra secreta. ')
        print(f'{nome_mand} esta mais feliz')
        print()
        digitadas.pop()


    for letra_secreta in secreto:
        if letra_secreta in digitadas:
            secreto_temporario += letra_secreta
        else:
            secreto_temporario += '*'

    if secreto_temporario == secreto:
        print()
        print(f'$$$$$ {nome_forc} $$$$$'.upper())
        print(f'Que legal, VOCE GANHOU !!! A palavra era {secreto_temporario}')
        print(f'Voce acertou na {contador} tentativa')
        break
    else:
        print()
        print(f'{secreto_temporario:=^50}')
        print(f'A palavra secreta esta assim: {secreto_temporario}')
        print(f'{secreto_temporario:=^50}')
        print()